name: "💡 Предложить фичу"
description: "Идея по улучшению доски"
title: "feat: "
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Что хочешь добавить?"
      placeholder: "Тир-лист позорников..."
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "Подробности (необязательно)"
      placeholder: "Как это должно выглядеть, как работать..."
